package ui;

import entity.*;

public class MainUI extends javax.swing.JFrame {

    int hedgehogNumber;
    int playerNumber;
    int winningNumber;

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        jDialog1.pack();
        jDialog1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        hedgehogCount = new javax.swing.JSpinner();
        winHedgehog = new javax.swing.JSpinner();
        obstacleType = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        playerCount = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        celll61 = new javax.swing.JButton();
        cell62 = new javax.swing.JButton();
        celll63 = new javax.swing.JButton();
        cell64 = new javax.swing.JButton();
        cell51 = new javax.swing.JButton();
        cell52 = new javax.swing.JButton();
        cell53 = new javax.swing.JButton();
        cell54 = new javax.swing.JButton();
        cell41 = new javax.swing.JButton();
        cell42 = new javax.swing.JButton();
        cell43 = new javax.swing.JButton();
        cell44 = new javax.swing.JButton();
        cell31 = new javax.swing.JButton();
        cell32 = new javax.swing.JButton();
        cell33 = new javax.swing.JButton();
        cell34 = new javax.swing.JButton();
        cell21 = new javax.swing.JButton();
        cell22 = new javax.swing.JButton();
        cell23 = new javax.swing.JButton();
        cell24 = new javax.swing.JButton();
        cell11 = new javax.swing.JButton();
        cell12 = new javax.swing.JButton();
        cell13 = new javax.swing.JButton();
        cell14 = new javax.swing.JButton();
        cell55 = new javax.swing.JButton();
        cell56 = new javax.swing.JButton();
        cell57 = new javax.swing.JButton();
        cell58 = new javax.swing.JButton();
        cell59 = new javax.swing.JButton();
        cell60 = new javax.swing.JButton();
        cell61 = new javax.swing.JButton();
        cell63 = new javax.swing.JButton();
        cell65 = new javax.swing.JButton();
        cell66 = new javax.swing.JButton();
        cell67 = new javax.swing.JButton();
        cell68 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        jDialog1.setAlwaysOnTop(true);

        hedgehogCount.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));

        winHedgehog.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        obstacleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Black Hole", "Deep Pit" }));

        jLabel1.setText("Number of Players");

        jLabel3.setText("Hedgehogs Per Player");

        jLabel4.setText("Hedgehog to Win");

        jLabel6.setText("Obstacle Type");

        startButton.setText("Start Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        playerCount.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(playerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(winHedgehog, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(obstacleType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(hedgehogCount, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hedgehogCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(winHedgehog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(obstacleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(startButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Next Player");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.LINE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(6, 5));

        celll61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        celll61.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        celll61.setContentAreaFilled(false);
        celll61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        celll61.setIconTextGap(0);
        celll61.setMargin(new java.awt.Insets(0, 0, 0, 0));
        celll61.setMaximumSize(new java.awt.Dimension(104, 104));
        celll61.setMinimumSize(new java.awt.Dimension(104, 104));
        celll61.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(celll61);

        cell62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell62.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell62.setContentAreaFilled(false);
        cell62.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell62.setIconTextGap(0);
        cell62.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell62.setMaximumSize(new java.awt.Dimension(104, 104));
        cell62.setMinimumSize(new java.awt.Dimension(104, 104));
        cell62.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell62);

        celll63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        celll63.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        celll63.setContentAreaFilled(false);
        celll63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        celll63.setIconTextGap(0);
        celll63.setMargin(new java.awt.Insets(0, 0, 0, 0));
        celll63.setMaximumSize(new java.awt.Dimension(104, 104));
        celll63.setMinimumSize(new java.awt.Dimension(104, 104));
        celll63.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(celll63);

        cell64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell64.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell64.setContentAreaFilled(false);
        cell64.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell64.setIconTextGap(0);
        cell64.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell64.setMaximumSize(new java.awt.Dimension(104, 104));
        cell64.setMinimumSize(new java.awt.Dimension(104, 104));
        cell64.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell64);

        cell51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell51.setContentAreaFilled(false);
        cell51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell51.setIconTextGap(0);
        cell51.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell51.setMaximumSize(new java.awt.Dimension(104, 104));
        cell51.setMinimumSize(new java.awt.Dimension(104, 104));
        cell51.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell51);

        cell52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell52.setContentAreaFilled(false);
        cell52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell52.setIconTextGap(0);
        cell52.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell52.setMaximumSize(new java.awt.Dimension(104, 104));
        cell52.setMinimumSize(new java.awt.Dimension(104, 104));
        cell52.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell52);

        cell53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell53.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell53.setContentAreaFilled(false);
        cell53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell53.setIconTextGap(0);
        cell53.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell53.setMaximumSize(new java.awt.Dimension(104, 104));
        cell53.setMinimumSize(new java.awt.Dimension(104, 104));
        cell53.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell53);

        cell54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell54.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell54.setContentAreaFilled(false);
        cell54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell54.setIconTextGap(0);
        cell54.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell54.setMaximumSize(new java.awt.Dimension(104, 104));
        cell54.setMinimumSize(new java.awt.Dimension(104, 104));
        cell54.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell54);

        cell41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell41.setContentAreaFilled(false);
        cell41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell41.setIconTextGap(0);
        cell41.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell41.setMaximumSize(new java.awt.Dimension(104, 104));
        cell41.setMinimumSize(new java.awt.Dimension(104, 104));
        cell41.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell41);

        cell42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell42.setContentAreaFilled(false);
        cell42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell42.setIconTextGap(0);
        cell42.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell42.setMaximumSize(new java.awt.Dimension(104, 104));
        cell42.setMinimumSize(new java.awt.Dimension(104, 104));
        cell42.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell42);

        cell43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell43.setContentAreaFilled(false);
        cell43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell43.setIconTextGap(0);
        cell43.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell43.setMaximumSize(new java.awt.Dimension(104, 104));
        cell43.setMinimumSize(new java.awt.Dimension(104, 104));
        cell43.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell43);

        cell44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell44.setContentAreaFilled(false);
        cell44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell44.setIconTextGap(0);
        cell44.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell44.setMaximumSize(new java.awt.Dimension(104, 104));
        cell44.setMinimumSize(new java.awt.Dimension(104, 104));
        cell44.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell44);

        cell31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell31.setContentAreaFilled(false);
        cell31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell31.setIconTextGap(0);
        cell31.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell31.setMaximumSize(new java.awt.Dimension(104, 104));
        cell31.setMinimumSize(new java.awt.Dimension(104, 104));
        cell31.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell31);

        cell32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell32.setContentAreaFilled(false);
        cell32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell32.setIconTextGap(0);
        cell32.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell32.setMaximumSize(new java.awt.Dimension(104, 104));
        cell32.setMinimumSize(new java.awt.Dimension(104, 104));
        cell32.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell32);

        cell33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell33.setContentAreaFilled(false);
        cell33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell33.setIconTextGap(0);
        cell33.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell33.setMaximumSize(new java.awt.Dimension(104, 104));
        cell33.setMinimumSize(new java.awt.Dimension(104, 104));
        cell33.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell33);

        cell34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell34.setContentAreaFilled(false);
        cell34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell34.setIconTextGap(0);
        cell34.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell34.setMaximumSize(new java.awt.Dimension(104, 104));
        cell34.setMinimumSize(new java.awt.Dimension(104, 104));
        cell34.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell34);

        cell21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell21.setContentAreaFilled(false);
        cell21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell21.setIconTextGap(0);
        cell21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell21.setMaximumSize(new java.awt.Dimension(104, 104));
        cell21.setMinimumSize(new java.awt.Dimension(104, 104));
        cell21.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell21);

        cell22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell22.setContentAreaFilled(false);
        cell22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell22.setIconTextGap(0);
        cell22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell22.setMaximumSize(new java.awt.Dimension(104, 104));
        cell22.setMinimumSize(new java.awt.Dimension(104, 104));
        cell22.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell22);

        cell23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell23.setContentAreaFilled(false);
        cell23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell23.setIconTextGap(0);
        cell23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell23.setMaximumSize(new java.awt.Dimension(104, 104));
        cell23.setMinimumSize(new java.awt.Dimension(104, 104));
        cell23.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell23);

        cell24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell24.setContentAreaFilled(false);
        cell24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell24.setIconTextGap(0);
        cell24.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell24.setMaximumSize(new java.awt.Dimension(104, 104));
        cell24.setMinimumSize(new java.awt.Dimension(104, 104));
        cell24.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell24);

        cell11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell11.setContentAreaFilled(false);
        cell11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell11.setIconTextGap(0);
        cell11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell11.setMaximumSize(new java.awt.Dimension(104, 104));
        cell11.setMinimumSize(new java.awt.Dimension(104, 104));
        cell11.setPreferredSize(new java.awt.Dimension(104, 104));
        cell11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cell11MouseClicked(evt);
            }
        });
        jPanel1.add(cell11);

        cell12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell12.setContentAreaFilled(false);
        cell12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell12.setIconTextGap(0);
        cell12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell12.setMaximumSize(new java.awt.Dimension(104, 104));
        cell12.setMinimumSize(new java.awt.Dimension(104, 104));
        cell12.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell12);

        cell13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell13.setContentAreaFilled(false);
        cell13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell13.setIconTextGap(0);
        cell13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell13.setMaximumSize(new java.awt.Dimension(104, 104));
        cell13.setMinimumSize(new java.awt.Dimension(104, 104));
        cell13.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell13);

        cell14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell14.setContentAreaFilled(false);
        cell14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell14.setIconTextGap(0);
        cell14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell14.setMaximumSize(new java.awt.Dimension(104, 104));
        cell14.setMinimumSize(new java.awt.Dimension(104, 104));
        cell14.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell14);

        cell55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell55.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell55.setContentAreaFilled(false);
        cell55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell55.setIconTextGap(0);
        cell55.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell55.setMaximumSize(new java.awt.Dimension(104, 104));
        cell55.setMinimumSize(new java.awt.Dimension(104, 104));
        cell55.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell55);

        cell56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell56.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell56.setContentAreaFilled(false);
        cell56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell56.setIconTextGap(0);
        cell56.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell56.setMaximumSize(new java.awt.Dimension(104, 104));
        cell56.setMinimumSize(new java.awt.Dimension(104, 104));
        cell56.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell56);

        cell57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell57.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell57.setContentAreaFilled(false);
        cell57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell57.setIconTextGap(0);
        cell57.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell57.setMaximumSize(new java.awt.Dimension(104, 104));
        cell57.setMinimumSize(new java.awt.Dimension(104, 104));
        cell57.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell57);

        cell58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell58.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell58.setContentAreaFilled(false);
        cell58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell58.setIconTextGap(0);
        cell58.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell58.setMaximumSize(new java.awt.Dimension(104, 104));
        cell58.setMinimumSize(new java.awt.Dimension(104, 104));
        cell58.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell58);

        cell59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell59.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell59.setContentAreaFilled(false);
        cell59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell59.setIconTextGap(0);
        cell59.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell59.setMaximumSize(new java.awt.Dimension(104, 104));
        cell59.setMinimumSize(new java.awt.Dimension(104, 104));
        cell59.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell59);

        cell60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell60.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell60.setContentAreaFilled(false);
        cell60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell60.setIconTextGap(0);
        cell60.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell60.setMaximumSize(new java.awt.Dimension(104, 104));
        cell60.setMinimumSize(new java.awt.Dimension(104, 104));
        cell60.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell60);

        cell61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell61.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell61.setContentAreaFilled(false);
        cell61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell61.setIconTextGap(0);
        cell61.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell61.setMaximumSize(new java.awt.Dimension(104, 104));
        cell61.setMinimumSize(new java.awt.Dimension(104, 104));
        cell61.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell61);

        cell63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell63.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell63.setContentAreaFilled(false);
        cell63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell63.setIconTextGap(0);
        cell63.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell63.setMaximumSize(new java.awt.Dimension(104, 104));
        cell63.setMinimumSize(new java.awt.Dimension(104, 104));
        cell63.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell63);

        cell65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell65.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell65.setContentAreaFilled(false);
        cell65.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell65.setIconTextGap(0);
        cell65.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell65.setMaximumSize(new java.awt.Dimension(104, 104));
        cell65.setMinimumSize(new java.awt.Dimension(104, 104));
        cell65.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell65);

        cell66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell66.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell66.setContentAreaFilled(false);
        cell66.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell66.setIconTextGap(0);
        cell66.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell66.setMaximumSize(new java.awt.Dimension(104, 104));
        cell66.setMinimumSize(new java.awt.Dimension(104, 104));
        cell66.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell66);

        cell67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell67.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell67.setContentAreaFilled(false);
        cell67.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell67.setIconTextGap(0);
        cell67.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell67.setMaximumSize(new java.awt.Dimension(104, 104));
        cell67.setMinimumSize(new java.awt.Dimension(104, 104));
        cell67.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell67);

        cell68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standardEnabledCell.png"))); // NOI18N
        cell68.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cell68.setContentAreaFilled(false);
        cell68.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cell68.setIconTextGap(0);
        cell68.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cell68.setMaximumSize(new java.awt.Dimension(104, 104));
        cell68.setMinimumSize(new java.awt.Dimension(104, 104));
        cell68.setPreferredSize(new java.awt.Dimension(104, 104));
        jPanel1.add(cell68);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arvin Ng\\Documents\\NetBeansProjects\\Assignment\\Assignment\\src\\main\\java\\images\\dice1.png")); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel2.setMaximumSize(new java.awt.Dimension(104, 104));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(104, 104));
        getContentPane().add(jLabel2, java.awt.BorderLayout.LINE_END);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Game");

        jMenuItem3.setText("New Game");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Quit Game");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setText("Game Rules");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("About");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        jDialog1.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        hedgehogNumber = (Integer) hedgehogCount.getValue();
        playerNumber = (Integer) playerCount.getValue();
        winningNumber = (Integer) winHedgehog.getValue();

        Board gameBoard = new Board(playerNumber, hedgehogNumber, playerNumber);
        jDialog1.setVisible(false);

    }//GEN-LAST:event_startButtonActionPerformed

    private void cell11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cell11MouseClicked

    }//GEN-LAST:event_cell11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cell11;
    private javax.swing.JButton cell12;
    private javax.swing.JButton cell13;
    private javax.swing.JButton cell14;
    private javax.swing.JButton cell21;
    private javax.swing.JButton cell22;
    private javax.swing.JButton cell23;
    private javax.swing.JButton cell24;
    private javax.swing.JButton cell31;
    private javax.swing.JButton cell32;
    private javax.swing.JButton cell33;
    private javax.swing.JButton cell34;
    private javax.swing.JButton cell41;
    private javax.swing.JButton cell42;
    private javax.swing.JButton cell43;
    private javax.swing.JButton cell44;
    private javax.swing.JButton cell51;
    private javax.swing.JButton cell52;
    private javax.swing.JButton cell53;
    private javax.swing.JButton cell54;
    private javax.swing.JButton cell55;
    private javax.swing.JButton cell56;
    private javax.swing.JButton cell57;
    private javax.swing.JButton cell58;
    private javax.swing.JButton cell59;
    private javax.swing.JButton cell60;
    private javax.swing.JButton cell61;
    private javax.swing.JButton cell62;
    private javax.swing.JButton cell63;
    private javax.swing.JButton cell64;
    private javax.swing.JButton cell65;
    private javax.swing.JButton cell66;
    private javax.swing.JButton cell67;
    private javax.swing.JButton cell68;
    private javax.swing.JButton celll61;
    private javax.swing.JButton celll63;
    private javax.swing.JSpinner hedgehogCount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> obstacleType;
    private javax.swing.JSpinner playerCount;
    private javax.swing.JButton startButton;
    private javax.swing.JSpinner winHedgehog;
    // End of variables declaration//GEN-END:variables
}
